"""Create category and article/category association

Revision ID: 0efa88a0bfbe
Revises: a3ab807c3e6f
Create Date: 2019-10-03 10:59:33.922984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efa88a0bfbe'
down_revision = 'a3ab807c3e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('blog_article_category_assoc',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_article_category_assoc')
    op.drop_table('blog_category')
    # ### end Alembic commands ###
