"""Initial commit

Revision ID: 5ae4d19b7efe
Revises: 
Create Date: 2019-10-03 13:27:25.700790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae4d19b7efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blog_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('article_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_name')
    )
    op.create_index(op.f('ix_blog_article_file_name'), 'blog_article', ['file_name'], unique=True)
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('misc_das_trader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=39), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_article_category_assoc',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_article_category_assoc')
    op.drop_table('misc_das_trader')
    op.drop_table('blog_category')
    op.drop_index(op.f('ix_blog_article_file_name'), table_name='blog_article')
    op.drop_table('blog_article')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
