"""Rename das_trader to misc_das_trader

Revision ID: 992f066a3904
Revises: 2985fc48c3b0
Create Date: 2019-07-25 07:08:16.266380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '992f066a3904'
down_revision = '2985fc48c3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misc_das_trader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=39), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('das_trader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('das_trader',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=39), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('misc_das_trader')
    # ### end Alembic commands ###
